# src/generate_data.py
"""
Dataset-level generator for sparse 2D tracking trajectories -> dense 3D beam displacement.

Final-testing version:
1. Observations are sampled on the continuous mesh surface, not only at vertices.
2. Each observed 2D track has mesh-surface correspondence:
      obs_face_id[k]
      obs_face_vertices[k] = [i1, i2, i3]
      obs_barycentric[k] = [w1, w2, w3]
3. Sparse soft correspondence ground truth is saved:
      W_gt_sparse_indices[k] = [i1, i2, i3]
      W_gt_sparse_values[k]  = [w1, w2, w3]
4. Optional dense W_gt can be saved with --save_dense_W.
5. y is generated by barycentric interpolation followed by pinhole projection:
      X_k = sum_j w_j X0[i_j]
      U_k(t) = sum_j w_j U_seq[t, i_j]
      y(t,k) = project(X_k + U_k(t)) - project(X_k)

Output:
    data/dataset_v2_surface/{train,val,test}/sample_XXXX/
"""

import os
import json
import argparse
from pathlib import Path

import numpy as np
import trimesh


# ============================================================
# Physics: Euler-Bernoulli cantilever first mode
# ============================================================

def cantilever_first_mode_shape(x, L):
    betaL = 1.875104068711961
    beta = betaL / L

    sigma = (
        (np.cosh(betaL) + np.cos(betaL)) /
        (np.sinh(betaL) + np.sin(betaL))
    )

    phi = (
        np.cosh(beta * x)
        - np.cos(beta * x)
        - sigma * (np.sinh(beta * x) - np.sin(beta * x))
    )

    phi = phi / (np.max(np.abs(phi)) + 1e-12)
    return phi.astype(np.float32)


def cantilever_first_natural_frequency(E, I, rho, A, L):
    betaL = 1.875104068711961
    omega1 = betaL ** 2 * np.sqrt(E * I / (rho * A * L ** 4))
    return float(omega1)


def generate_free_vibration(
    X0,
    youngs_modulus,
    density,
    width,
    height,
    length,
    amplitude,
    T,
    duration,
    length_axis=0,
    displacement_axis=1,
    phase=0.0,
    frequency_scale=1.0,
):
    """
    First-mode free vibration:
        U(x,t) = amplitude * phi_1(x) * cos(frequency_scale * omega_1 * t + phase)
    """
    area = width * height

    # Keep previous convention to avoid changing existing behaviour.
    inertia = height * (width ** 3) / 12.0

    omega1_base = cantilever_first_natural_frequency(
        youngs_modulus, inertia, density, area, length
    )
    omega1 = float(frequency_scale * omega1_base)

    x_raw = X0[:, length_axis]
    x = x_raw - x_raw.min()
    x = x / (x.max() + 1e-12) * length

    phi = cantilever_first_mode_shape(x, length)

    U = np.zeros_like(X0, dtype=np.float32)
    U[:, displacement_axis] = amplitude * phi

    t = np.linspace(0.0, duration, T, dtype=np.float32)
    amp_t = np.cos(omega1 * t + phase).astype(np.float32)

    U_seq = amp_t[:, None, None] * U[None, :, :]

    return {
        "U": U.astype(np.float32),
        "U_seq": U_seq.astype(np.float32),
        "amp_t": amp_t.astype(np.float32),
        "phi_1": phi.astype(np.float32),
        "omega1_base": omega1_base,
        "omega1": omega1,
        "area": area,
        "inertia": inertia,
    }


# ============================================================
# Camera: pinhole perspective camera
# ============================================================

def make_camera_intrinsics(fx, fy, cx, cy):
    return np.array(
        [[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]],
        dtype=np.float32,
    )


def look_at_camera(eye, target, up=np.array([0.0, 0.0, 1.0], dtype=np.float32)):
    eye = np.asarray(eye, dtype=np.float32)
    target = np.asarray(target, dtype=np.float32)
    up = np.asarray(up, dtype=np.float32)

    z_axis = target - eye
    z_axis = z_axis / (np.linalg.norm(z_axis) + 1e-8)

    x_axis = np.cross(z_axis, up)
    x_norm = np.linalg.norm(x_axis)

    if x_norm < 1e-6:
        up = np.array([0.0, 1.0, 0.0], dtype=np.float32)
        x_axis = np.cross(z_axis, up)
        x_norm = np.linalg.norm(x_axis)

    x_axis = x_axis / (x_norm + 1e-8)

    y_axis = np.cross(x_axis, z_axis)
    y_axis = y_axis / (np.linalg.norm(y_axis) + 1e-8)

    R = np.stack([x_axis, y_axis, z_axis], axis=0)
    t = -R @ eye

    return R.astype(np.float32), t.astype(np.float32)


def perspective_project(X_world, K, R, t):
    X_cam = np.einsum("ij,...j->...i", R, X_world) + t

    z = X_cam[..., 2:3]
    z_safe = np.maximum(z, 1e-6)

    x_norm = X_cam[..., 0:1] / z_safe
    y_norm = X_cam[..., 1:2] / z_safe

    u = K[0, 0] * x_norm + K[0, 2]
    v = K[1, 1] * y_norm + K[1, 2]

    uv = np.concatenate([u, v], axis=-1)
    return uv.astype(np.float32), X_cam.astype(np.float32)


# ============================================================
# Sampling utilities
# ============================================================

def sample_camera_eye(rng, X0, length_axis=0, radius_range=(1.8, 3.0), elev_range=(0.2, 0.9)):
    center = X0.mean(axis=0).astype(np.float32)
    x_min = float(X0[:, length_axis].min())
    x_max = float(X0[:, length_axis].max())

    target = center.copy()
    target[length_axis] = rng.uniform(
        x_min + 0.35 * (x_max - x_min),
        x_min + 0.85 * (x_max - x_min),
    )

    radius = rng.uniform(radius_range[0], radius_range[1])
    azimuth = rng.uniform(0.0, 2.0 * np.pi)
    elev = rng.uniform(elev_range[0], elev_range[1])

    eye = target.copy()
    eye[0] += radius * np.cos(azimuth)
    eye[1] += radius * np.sin(azimuth)
    eye[2] += elev

    return eye.astype(np.float32), target.astype(np.float32)


def sample_barycentric_points(rng, n):
    """Uniformly sample barycentric coordinates inside triangles."""
    r1 = rng.random(n).astype(np.float32)
    r2 = rng.random(n).astype(np.float32)

    sqrt_r1 = np.sqrt(r1)
    w1 = 1.0 - sqrt_r1
    w2 = sqrt_r1 * (1.0 - r2)
    w3 = sqrt_r1 * r2

    return np.stack([w1, w2, w3], axis=1).astype(np.float32)


def triangle_areas(X0, faces):
    v0 = X0[faces[:, 0]]
    v1 = X0[faces[:, 1]]
    v2 = X0[faces[:, 2]]
    area = 0.5 * np.linalg.norm(np.cross(v1 - v0, v2 - v0), axis=1)
    return area.astype(np.float64)


def select_candidate_faces(X0, faces, length_axis=0, free_end_ratio=0.10):
    """Select faces whose centroid is in the free-end region."""
    centroids = X0[faces].mean(axis=1)
    x = centroids[:, length_axis]
    x_min = float(X0[:, length_axis].min())
    x_max = float(X0[:, length_axis].max())
    threshold = x_max - free_end_ratio * (x_max - x_min)

    candidate_face_id = np.where(x >= threshold)[0].astype(np.int64)
    if len(candidate_face_id) == 0:
        raise ValueError(f"No candidate faces found in the last {free_end_ratio * 100:.1f}% of the beam.")
    return candidate_face_id


def sample_observed_surface_points(X0, faces, rng, K_obs, length_axis=0, free_end_ratio=0.10, area_weighted=True):
    """
    Sample K observation locations on the mesh surface.

    Returns:
        obs_face_id       [K]
        obs_face_vertices [K,3]
        obs_barycentric   [K,3]
        X_obs0            [K,3]
        observed_idx      [K] compatibility: vertex with largest barycentric weight
        candidate_face_id [F_candidate]
    """
    candidate_face_id = select_candidate_faces(X0, faces, length_axis, free_end_ratio)

    if area_weighted:
        areas = triangle_areas(X0, faces)
        prob = areas[candidate_face_id]
        prob = prob / (prob.sum() + 1e-12)
        obs_face_id = rng.choice(candidate_face_id, size=K_obs, replace=True, p=prob)
    else:
        obs_face_id = rng.choice(candidate_face_id, size=K_obs, replace=True)

    obs_face_id = obs_face_id.astype(np.int64)
    obs_face_vertices = faces[obs_face_id].astype(np.int64)
    obs_barycentric = sample_barycentric_points(rng, K_obs)

    X_tri = X0[obs_face_vertices]  # [K,3,3]
    X_obs0 = np.sum(obs_barycentric[:, :, None] * X_tri, axis=1).astype(np.float32)

    dominant_corner = np.argmax(obs_barycentric, axis=1)
    observed_idx = obs_face_vertices[np.arange(K_obs), dominant_corner].astype(np.int64)

    return obs_face_id, obs_face_vertices, obs_barycentric, X_obs0, observed_idx, candidate_face_id.astype(np.int64)


def interpolate_surface_displacement(U_seq, obs_face_vertices, obs_barycentric):
    """
    U_seq: [T,N,3]
    obs_face_vertices: [K,3]
    obs_barycentric: [K,3]

    Returns:
        U_obs_seq: [T,K,3]
    """
    U_tri = U_seq[:, obs_face_vertices, :]  # [T,K,3,3]
    U_obs_seq = np.sum(obs_barycentric[None, :, :, None] * U_tri, axis=2)
    return U_obs_seq.astype(np.float32)


def make_dense_W_gt(N, obs_face_vertices, obs_barycentric):
    K_obs = obs_face_vertices.shape[0]
    W = np.zeros((K_obs, N), dtype=np.float32)
    for k in range(K_obs):
        for j in range(3):
            W[k, obs_face_vertices[k, j]] += obs_barycentric[k, j]
    return W


def make_sparse_W_gt(obs_face_vertices, obs_barycentric):
    return obs_face_vertices.astype(np.int64), obs_barycentric.astype(np.float32)


# ============================================================
# Single sample generation
# ============================================================

def generate_sample(
    mesh,
    mesh_path,
    output_dir,
    seed=0,
    split="train",
    sample_id=0,
    youngs_modulus=69e9,
    density=2700.0,
    width=0.05,
    height=0.10,
    length=1.0,
    amplitude=0.03,
    T=200,
    duration=1.0,
    K_obs=20,
    noise_std=1e-5,
    length_axis=0,
    displacement_axis=1,
    fx=800.0,
    fy=800.0,
    cx=320.0,
    cy=240.0,
    camera_eye=None,
    camera_target=None,
    normalize_y=True,
    free_end_ratio=0.10,
    phase=0.0,
    frequency_scale=1.0,
    observation_mode="surface",
    area_weighted_surface=True,
    save_dense_W=False,
):
    os.makedirs(output_dir, exist_ok=True)
    rng = np.random.default_rng(seed)

    X0 = np.asarray(mesh.vertices, dtype=np.float32)
    faces = np.asarray(mesh.faces, dtype=np.int64)
    if faces is None or len(faces) == 0:
        raise ValueError("Mesh has no triangular faces. Surface observation requires mesh.faces.")
    N = X0.shape[0]

    vib = generate_free_vibration(
        X0=X0,
        youngs_modulus=youngs_modulus,
        density=density,
        width=width,
        height=height,
        length=length,
        amplitude=amplitude,
        T=T,
        duration=duration,
        length_axis=length_axis,
        displacement_axis=displacement_axis,
        phase=phase,
        frequency_scale=frequency_scale,
    )

    U = vib["U"]
    U_seq = vib["U_seq"]
    amp_t = vib["amp_t"]
    phi_1 = vib["phi_1"]

    if observation_mode == "surface":
        obs_face_id, obs_face_vertices, obs_barycentric, X_obs0, observed_idx, candidate_face_id = sample_observed_surface_points(
            X0=X0,
            faces=faces,
            rng=rng,
            K_obs=K_obs,
            length_axis=length_axis,
            free_end_ratio=free_end_ratio,
            area_weighted=area_weighted_surface,
        )
        U_obs_seq = interpolate_surface_displacement(U_seq, obs_face_vertices, obs_barycentric)
        W_sparse_indices, W_sparse_values = make_sparse_W_gt(obs_face_vertices, obs_barycentric)
        W_gt_dense = make_dense_W_gt(N, obs_face_vertices, obs_barycentric) if save_dense_W else None

    elif observation_mode == "vertex":
        x_coord = X0[:, length_axis]
        x_max = x_coord.max()
        x_min = x_coord.min()
        threshold = x_max - free_end_ratio * (x_max - x_min)
        candidate_idx = np.where(x_coord >= threshold)[0]
        if len(candidate_idx) < K_obs:
            raise ValueError(f"Not enough free-end vertices for K_obs={K_obs}.")

        observed_idx = np.sort(rng.choice(candidate_idx, size=K_obs, replace=False)).astype(np.int64)
        X_obs0 = X0[observed_idx]
        U_obs_seq = U_seq[:, observed_idx, :]

        vertex_to_face = {}
        for f_id, tri in enumerate(faces):
            for local_j, vid in enumerate(tri):
                if int(vid) not in vertex_to_face:
                    vertex_to_face[int(vid)] = (f_id, local_j)

        obs_face_id = []
        obs_face_vertices = []
        obs_barycentric = []
        for vid in observed_idx:
            if int(vid) in vertex_to_face:
                f_id, local_j = vertex_to_face[int(vid)]
                tri = faces[f_id]
                bary = np.zeros(3, dtype=np.float32)
                bary[local_j] = 1.0
            else:
                f_id = 0
                tri = faces[0]
                bary = np.array([1.0, 0.0, 0.0], dtype=np.float32)
            obs_face_id.append(f_id)
            obs_face_vertices.append(tri)
            obs_barycentric.append(bary)

        obs_face_id = np.asarray(obs_face_id, dtype=np.int64)
        obs_face_vertices = np.asarray(obs_face_vertices, dtype=np.int64)
        obs_barycentric = np.asarray(obs_barycentric, dtype=np.float32)
        candidate_face_id = np.unique(obs_face_id).astype(np.int64)
        W_sparse_indices, W_sparse_values = make_sparse_W_gt(obs_face_vertices, obs_barycentric)
        W_gt_dense = make_dense_W_gt(N, obs_face_vertices, obs_barycentric) if save_dense_W else None

    else:
        raise ValueError(f"Unknown observation_mode: {observation_mode}")

    K = make_camera_intrinsics(fx, fy, cx, cy)

    if camera_eye is None or camera_target is None:
        camera_eye, camera_target = sample_camera_eye(rng=rng, X0=X0, length_axis=length_axis)
    else:
        camera_eye = np.asarray(camera_eye, dtype=np.float32)
        camera_target = np.asarray(camera_target, dtype=np.float32)

    R, t = look_at_camera(camera_eye, camera_target)

    uv0, Xcam0 = perspective_project(X_obs0, K, R, t)
    uvt, Xcamt = perspective_project(X_obs0[None, :, :] + U_obs_seq, K, R, t)

    if np.any(Xcam0[:, 2] <= 1e-6) or np.any(Xcamt[..., 2] <= 1e-6):
        raise RuntimeError(f"Invalid camera for sample {sample_id}: some points are behind the camera.")

    y_pixel_clean = uvt - uv0[None, :, :]

    if normalize_y:
        y_clean = y_pixel_clean / fx
        y_unit = f"normalized pixel displacement, divided by fx={fx}"
    else:
        y_clean = y_pixel_clean
        y_unit = "pixel displacement"

    if noise_std > 0:
        noise = rng.normal(scale=noise_std, size=y_clean.shape).astype(np.float32)
    else:
        noise = np.zeros_like(y_clean, dtype=np.float32)

    y = (y_clean + noise).astype(np.float32)

    deformed_mesh = mesh.copy()
    deformed_mesh.vertices = X0 + U

    # Core files
    np.save(os.path.join(output_dir, "X0.npy"), X0.astype(np.float32))
    np.save(os.path.join(output_dir, "faces.npy"), faces.astype(np.int64))
    np.save(os.path.join(output_dir, "U.npy"), U.astype(np.float32))
    np.save(os.path.join(output_dir, "U_seq.npy"), U_seq.astype(np.float32))

    # Observation files
    np.save(os.path.join(output_dir, "y.npy"), y.astype(np.float32))
    np.save(os.path.join(output_dir, "y_clean.npy"), y_clean.astype(np.float32))
    np.save(os.path.join(output_dir, "y_pixel.npy"), y_pixel_clean.astype(np.float32))
    np.save(os.path.join(output_dir, "track_uv0.npy"), uv0.astype(np.float32))
    np.save(os.path.join(output_dir, "track_uv_seq.npy"), uvt.astype(np.float32))

    # Surface correspondence files
    np.save(os.path.join(output_dir, "obs_face_id.npy"), obs_face_id.astype(np.int64))
    np.save(os.path.join(output_dir, "obs_face_vertices.npy"), obs_face_vertices.astype(np.int64))
    np.save(os.path.join(output_dir, "obs_barycentric.npy"), obs_barycentric.astype(np.float32))
    np.save(os.path.join(output_dir, "W_gt_sparse_indices.npy"), W_sparse_indices.astype(np.int64))
    np.save(os.path.join(output_dir, "W_gt_sparse_values.npy"), W_sparse_values.astype(np.float32))
    if W_gt_dense is not None:
        np.save(os.path.join(output_dir, "W_gt_dense.npy"), W_gt_dense.astype(np.float32))

    # Backward compatibility
    np.save(os.path.join(output_dir, "observed_idx.npy"), observed_idx.astype(np.int64))
    np.save(os.path.join(output_dir, "candidate_free_end_face_id.npy"), candidate_face_id.astype(np.int64))

    # Camera files
    np.save(os.path.join(output_dir, "camera_K.npy"), K.astype(np.float32))
    np.save(os.path.join(output_dir, "camera_R.npy"), R.astype(np.float32))
    np.save(os.path.join(output_dir, "camera_t.npy"), t.astype(np.float32))
    np.save(os.path.join(output_dir, "camera_eye.npy"), camera_eye.astype(np.float32))
    np.save(os.path.join(output_dir, "camera_target.npy"), camera_target.astype(np.float32))

    # Physics files
    np.save(os.path.join(output_dir, "amp_t.npy"), amp_t.astype(np.float32))
    np.save(os.path.join(output_dir, "phi_1.npy"), phi_1.astype(np.float32))

    deformed_mesh.export(os.path.join(output_dir, "deformed_mesh.obj"))

    meta = {
        "mesh_path": str(mesh_path),
        "output_dir": str(output_dir),
        "split": split,
        "sample_id": int(sample_id),
        "seed": int(seed),
        "model": "Euler-Bernoulli cantilever first-mode free vibration",
        "physical_equation": "u(x,t) = A * phi_1(x) * cos(omega_1 * t + phase)",
        "youngs_modulus": float(youngs_modulus),
        "density": float(density),
        "width": float(width),
        "height": float(height),
        "area": float(vib["area"]),
        "moment_inertia": float(vib["inertia"]),
        "length": float(length),
        "amplitude": float(amplitude),
        "phase": float(phase),
        "frequency_scale": float(frequency_scale),
        "T": int(T),
        "duration": float(duration),
        "K_obs": int(K_obs),
        "free_end_ratio": float(free_end_ratio),
        "noise_std": float(noise_std),
        "length_axis": int(length_axis),
        "displacement_axis": int(displacement_axis),
        "omega1_base_rad_per_s": float(vib["omega1_base"]),
        "omega1_rad_per_s": float(vib["omega1"]),
        "frequency_hz": float(vib["omega1"] / (2.0 * np.pi)),
        "X0_shape": list(X0.shape),
        "faces_shape": list(faces.shape),
        "U_shape": list(U.shape),
        "U_seq_shape": list(U_seq.shape),
        "y_shape": list(y.shape),
        "projection": "pinhole perspective camera",
        "camera_intrinsics": {"fx": float(fx), "fy": float(fy), "cx": float(cx), "cy": float(cy)},
        "camera_eye": camera_eye.tolist(),
        "camera_target": camera_target.tolist(),
        "observation_mode": observation_mode,
        "correspondence_type": "surface barycentric soft correspondence" if observation_mode == "surface" else "vertex one-hot correspondence",
        "surface_files": {
            "obs_face_id": "obs_face_id.npy",
            "obs_face_vertices": "obs_face_vertices.npy",
            "obs_barycentric": "obs_barycentric.npy",
            "W_gt_sparse_indices": "W_gt_sparse_indices.npy",
            "W_gt_sparse_values": "W_gt_sparse_values.npy",
            "W_gt_dense": "W_gt_dense.npy" if save_dense_W else None,
        },
        "y_unit": y_unit,
        "y_pixel_max_abs": float(np.max(np.abs(y_pixel_clean))),
        "y_max_abs": float(np.max(np.abs(y))),
        "U_max_abs": float(np.max(np.abs(U_seq))),
        "observed_idx_min_compat": int(observed_idx.min()),
        "observed_idx_max_compat": int(observed_idx.max()),
        "save_dense_W": bool(save_dense_W),
    }

    with open(os.path.join(output_dir, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    split_info = {
        "split": split,
        "sample_id": int(sample_id),
        "seed": int(seed),
        "observation_mode": observation_mode,
        "obs_face_id": obs_face_id.tolist(),
        "obs_face_vertices": obs_face_vertices.tolist(),
        "obs_barycentric": obs_barycentric.tolist(),
        "observed_idx_compat": observed_idx.tolist(),
        "camera_eye": camera_eye.tolist(),
        "camera_target": camera_target.tolist(),
        "amplitude": float(amplitude),
        "phase": float(phase),
        "frequency_scale": float(frequency_scale),
        "noise_std": float(noise_std),
    }
    with open(os.path.join(output_dir, "split_info.json"), "w", encoding="utf-8") as f:
        json.dump(split_info, f, indent=2)

    return meta


# ============================================================
# Dataset generation
# ============================================================

def generate_dataset(args):
    mesh_path = Path(args.mesh_path)
    output_dir = Path(args.output_dir)

    if not mesh_path.exists():
        raise FileNotFoundError(f"Cannot find mesh file: {mesh_path.resolve()}\nPlease check --mesh_path.")

    print("=" * 80)
    print("Generating dataset")
    print("mesh_path:", mesh_path.resolve())
    print("output_dir:", output_dir.resolve())
    print("observation_mode:", args.observation_mode)
    print("=" * 80)

    mesh = trimesh.load_mesh(str(mesh_path), process=False)
    if mesh.vertices is None or len(mesh.vertices) == 0:
        raise ValueError(f"Loaded mesh has no vertices: {mesh_path}")
    if mesh.faces is None or len(mesh.faces) == 0:
        raise ValueError(f"Loaded mesh has no faces: {mesh_path}")

    dataset_rng = np.random.default_rng(args.seed)

    split_specs = [("train", args.num_train), ("val", args.num_val), ("test", args.num_test)]

    dataset_meta = {
        "mesh_path": str(mesh_path),
        "output_dir": str(output_dir),
        "seed": int(args.seed),
        "fair_split_rule": (
            "Same beam geometry. Train/val/test are split by sample, not by frame. "
            "Each sample has its own surface observation points, camera, amplitude, phase, frequency_scale, and noise."
        ),
        "observation_mode": args.observation_mode,
        "correspondence_type": "surface barycentric soft correspondence" if args.observation_mode == "surface" else "vertex one-hot correspondence",
        "num_train": int(args.num_train),
        "num_val": int(args.num_val),
        "num_test": int(args.num_test),
        "T": int(args.T),
        "K_obs": int(args.K_obs),
        "free_end_ratio": float(args.free_end_ratio),
        "amplitude_range": [float(args.amp_min), float(args.amp_max)],
        "frequency_scale_range": [float(args.freq_scale_min), float(args.freq_scale_max)],
        "noise_std_range": [float(args.noise_std_min), float(args.noise_std_max)],
        "normalize_y": bool(not args.no_normalize_y),
        "save_dense_W": bool(args.save_dense_W),
        "notes": (
            "For real-video-style testing, model input can be 2D tracking trajectories y. "
            "The barycentric files provide synthetic ground-truth soft correspondence for W supervision."
        ),
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "dataset_meta.json", "w", encoding="utf-8") as f:
        json.dump(dataset_meta, f, indent=2)

    all_summaries = []

    for split, count in split_specs:
        split_dir = output_dir / split
        split_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n[{split}] generating {count} samples")

        for i in range(count):
            sample_seed = int(dataset_rng.integers(0, 2**31 - 1))
            rng = np.random.default_rng(sample_seed)

            amplitude = float(rng.uniform(args.amp_min, args.amp_max))
            phase = float(rng.uniform(0.0, 2.0 * np.pi))
            frequency_scale = float(rng.uniform(args.freq_scale_min, args.freq_scale_max))
            noise_std = float(rng.uniform(args.noise_std_min, args.noise_std_max))

            sample_dir = split_dir / f"sample_{i:04d}"

            meta = generate_sample(
                mesh=mesh,
                mesh_path=mesh_path,
                output_dir=sample_dir,
                seed=sample_seed,
                split=split,
                sample_id=i,
                youngs_modulus=args.youngs_modulus,
                density=args.density,
                width=args.width,
                height=args.height,
                length=args.length,
                amplitude=amplitude,
                T=args.T,
                duration=args.duration,
                K_obs=args.K_obs,
                noise_std=noise_std,
                length_axis=args.length_axis,
                displacement_axis=args.displacement_axis,
                fx=args.fx,
                fy=args.fy,
                cx=args.cx,
                cy=args.cy,
                camera_eye=None,
                camera_target=None,
                normalize_y=not args.no_normalize_y,
                free_end_ratio=args.free_end_ratio,
                phase=phase,
                frequency_scale=frequency_scale,
                observation_mode=args.observation_mode,
                area_weighted_surface=not args.no_area_weighted_surface,
                save_dense_W=args.save_dense_W,
            )

            all_summaries.append({
                "split": split,
                "sample": f"sample_{i:04d}",
                "seed": sample_seed,
                "observation_mode": meta["observation_mode"],
                "correspondence_type": meta["correspondence_type"],
                "amplitude": meta["amplitude"],
                "frequency_hz": meta["frequency_hz"],
                "phase": meta["phase"],
                "noise_std": meta["noise_std"],
                "y_pixel_max_abs": meta["y_pixel_max_abs"],
                "y_max_abs": meta["y_max_abs"],
                "U_max_abs": meta["U_max_abs"],
            })

            if (i + 1) % max(1, args.print_every) == 0 or (i + 1) == count:
                print(
                    f"  {split} {i + 1:04d}/{count:04d} | "
                    f"A={amplitude:.5f}, freq_scale={frequency_scale:.3f}, "
                    f"noise={noise_std:.2e}, y_pix_max={meta['y_pixel_max_abs']:.3f}, "
                    f"U_max={meta['U_max_abs']:.4f}"
                )

    with open(output_dir / "samples_summary.json", "w", encoding="utf-8") as f:
        json.dump(all_summaries, f, indent=2)

    print("\nDone.")
    print("Dataset saved to:", output_dir.resolve())
    print("Next:")
    print(f"  python src\\check_data.py --data_dir {output_dir}\\train\\sample_0000")


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--mesh_path", type=str, default=r".\base_beams\beam.obj")
    parser.add_argument("--output_dir", type=str, default=r".\data\dataset_v2_surface")
    parser.add_argument("--seed", type=int, default=0)

    parser.add_argument("--num_train", type=int, default=100)
    parser.add_argument("--num_val", type=int, default=20)
    parser.add_argument("--num_test", type=int, default=30)

    parser.add_argument("--T", type=int, default=200)
    parser.add_argument("--K_obs", type=int, default=20)
    parser.add_argument("--duration", type=float, default=1.0)
    parser.add_argument("--free_end_ratio", type=float, default=0.10)

    parser.add_argument("--observation_mode", type=str, default="surface", choices=["surface", "vertex"])
    parser.add_argument("--no_area_weighted_surface", action="store_true")
    parser.add_argument("--save_dense_W", action="store_true")

    parser.add_argument("--amp_min", type=float, default=0.015)
    parser.add_argument("--amp_max", type=float, default=0.035)
    parser.add_argument("--freq_scale_min", type=float, default=0.80)
    parser.add_argument("--freq_scale_max", type=float, default=1.20)

    parser.add_argument("--length", type=float, default=1.0)
    parser.add_argument("--width", type=float, default=0.05)
    parser.add_argument("--height", type=float, default=0.10)
    parser.add_argument("--youngs_modulus", type=float, default=69e9)
    parser.add_argument("--density", type=float, default=2700.0)

    parser.add_argument("--noise_std_min", type=float, default=0.0)
    parser.add_argument("--noise_std_max", type=float, default=1e-5)

    parser.add_argument("--length_axis", type=int, default=0)
    parser.add_argument("--displacement_axis", type=int, default=1)

    parser.add_argument("--fx", type=float, default=800.0)
    parser.add_argument("--fy", type=float, default=800.0)
    parser.add_argument("--cx", type=float, default=320.0)
    parser.add_argument("--cy", type=float, default=240.0)

    parser.add_argument("--no_normalize_y", action="store_true")
    parser.add_argument("--print_every", type=int, default=10)

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate_dataset(args)
