# src/train.py
"""
Final training script for surface-correspondence Bayesian inversion.

This version is designed for dataset_v2_surface generated by the new generate_data.py.

Core idea:
    Input:
        y_t: sparse 2D tracking displacement, [K,2]

    Model predicts:
        U_mu_norm:     dense displacement mean in normalized U-space, [N,3]
        U_logvar_norm: dense displacement log-variance in normalized U-space, [N,3]
        W_logits:      soft correspondence logits, [K,N]
        z_mu, z_logvar

    Differentiable observation operator:
        W = softmax(W_logits, dim=-1)
        X_k = sum_i W[k,i] X0_i
        U_k = sum_i W[k,i] U_i
        y_hat_k = project(X_k + U_k) - project(X_k)

    Training loss:
        L = lambda_obs * L_obs(y, y_hat)
          + lambda_U   * L_U(U_gt, U_mu, U_logvar)
          + lambda_W   * L_W(W_gt, W_logits)
          + beta_kl    * KL(q(z|y)||N(0,I))

Important:
    - observed_idx is NOT used as model input.
    - W_gt comes from surface barycentric correspondence:
        W_gt_sparse_indices.npy [K,3]
        W_gt_sparse_values.npy  [K,3]
    - Observation loss is computed in physical normalized-pixel y-space.
    - U auxiliary loss is computed in normalized U-space.
"""

from models.joint_uw_model import JointUWProbabilisticMLP
from geometry.observation import observation_operator_softW, observation_operator_gtW
from losses.loss_core import kl_loss, gaussian_nll_loss, mse_loss, soft_ce_loss_from_sparse


import os
import csv
import glob
import json
import argparse
import random
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader


# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_DATA_DIR = os.path.join(PROJECT_ROOT, "data", "dataset_v2_surface", "train")
DEFAULT_WEIGHT_DIR = os.path.join(PROJECT_ROOT, "outputs", "weights")
DEFAULT_LOG_DIR = os.path.join(PROJECT_ROOT, "outputs", "logs")


# ============================================================
# Utilities
# ============================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def safe_torch_save(obj, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp_path = path + ".tmp"
    torch.save(obj, tmp_path)
    os.replace(tmp_path, path)


class SurfaceFrameDataset(Dataset):
    """
    Frame-level dataset for surface-correspondence training.

    Each item returns:
        y_norm_flat:      [2K]
        y_phys:           [K,2]
        U_norm_flat:      [3N]
        U_phys:           [N,3]
        X0:               [N,3]
        W_sparse_idx:     [K,3]
        W_sparse_val:     [K,3]
        camera_K:         [3,3]
        camera_R:         [3,3]
        camera_t:         [3]
        sample_id:        int
        frame_id:         int

    Normalization:
        y_mean/y_std and U_mean/U_std are computed from training split only.
    """

    def __init__(self, root: str):
        self.root = root
        self.sample_dirs = sorted(glob.glob(os.path.join(root, "sample_*")))

        if len(self.sample_dirs) == 0:
            raise ValueError(
                f"No sample_* folders found in {root}. "
                f"Expected data/dataset_v2_surface/train/sample_XXXX."
            )

        # Per-sample storage.
        self.samples: List[Dict] = []
        y_all = []
        U_all = []

        for sid, d in enumerate(self.sample_dirs):
            required = [
                "X0.npy",
                "U_seq.npy",
                "y.npy",
                "W_gt_sparse_indices.npy",
                "W_gt_sparse_values.npy",
                "camera_K.npy",
                "camera_R.npy",
                "camera_t.npy",
            ]
            for f in required:
                p = os.path.join(d, f)
                if not os.path.exists(p):
                    raise FileNotFoundError(f"Missing required file: {p}")

            X0 = np.load(os.path.join(d, "X0.npy")).astype(np.float32)                 # [N,3]
            U_seq = np.load(os.path.join(d, "U_seq.npy")).astype(np.float32)           # [T,N,3]
            y = np.load(os.path.join(d, "y.npy")).astype(np.float32)                   # [T,K,2]
            W_idx = np.load(os.path.join(d, "W_gt_sparse_indices.npy")).astype(np.int64)  # [K,3]
            W_val = np.load(os.path.join(d, "W_gt_sparse_values.npy")).astype(np.float32) # [K,3]
            camera_K = np.load(os.path.join(d, "camera_K.npy")).astype(np.float32)
            camera_R = np.load(os.path.join(d, "camera_R.npy")).astype(np.float32)
            camera_t = np.load(os.path.join(d, "camera_t.npy")).astype(np.float32)

            if y.ndim != 3 or y.shape[-1] != 2:
                raise ValueError(f"Expected y [T,K,2], got {y.shape} in {d}")
            if U_seq.ndim != 3 or U_seq.shape[-1] != 3:
                raise ValueError(f"Expected U_seq [T,N,3], got {U_seq.shape} in {d}")
            if W_idx.shape != W_val.shape or W_idx.ndim != 2 or W_idx.shape[1] != 3:
                raise ValueError(f"Expected W sparse [K,3], got {W_idx.shape}, {W_val.shape} in {d}")

            T = min(y.shape[0], U_seq.shape[0])
            y = y[:T]
            U_seq = U_seq[:T]

            y_flat = y.reshape(T, -1)
            U_flat = U_seq.reshape(T, -1)

            y_all.append(y_flat)
            U_all.append(U_flat)

            self.samples.append({
                "dir": d,
                "X0": X0,
                "U_seq": U_seq,
                "y": y,
                "W_idx": W_idx,
                "W_val": W_val,
                "camera_K": camera_K,
                "camera_R": camera_R,
                "camera_t": camera_t,
                "T": T,
                "N": X0.shape[0],
                "K": y.shape[1],
            })

        y_all_np = np.concatenate(y_all, axis=0).astype(np.float32)
        U_all_np = np.concatenate(U_all, axis=0).astype(np.float32)

        self.y_mean = y_all_np.mean(axis=0, keepdims=True).astype(np.float32)
        self.y_std = (y_all_np.std(axis=0, keepdims=True) + 1e-8).astype(np.float32)

        self.U_mean = U_all_np.mean(axis=0, keepdims=True).astype(np.float32)
        self.U_std = (U_all_np.std(axis=0, keepdims=True) + 1e-8).astype(np.float32)

        # Flatten frame index.
        self.frame_index = []
        for sid, s in enumerate(self.samples):
            for t in range(s["T"]):
                self.frame_index.append((sid, t))

        # Dimensional consistency.
        Ns = sorted(set(s["N"] for s in self.samples))
        Ks = sorted(set(s["K"] for s in self.samples))
        if len(Ns) != 1:
            raise ValueError(f"All samples must have same N for current MLP model. Got {Ns}")
        if len(Ks) != 1:
            raise ValueError(f"All samples must have same K. Got {Ks}")

        self.N = Ns[0]
        self.K = Ks[0]
        self.y_dim = 2 * self.K
        self.U_dim = 3 * self.N

        print("Loaded surface dataset")
        print("  root:", os.path.abspath(root))
        print("  num samples:", len(self.samples))
        print("  num frames:", len(self.frame_index))
        print("  N vertices:", self.N)
        print("  K tracks:", self.K)
        print("  y_dim:", self.y_dim)
        print("  U_dim:", self.U_dim)
        print("  y mean/std:", float(self.y_mean.mean()), float(self.y_std.mean()))
        print("  U mean/std:", float(self.U_mean.mean()), float(self.U_std.mean()))

    def __len__(self):
        return len(self.frame_index)

    def __getitem__(self, idx):
        sid, tid = self.frame_index[idx]
        s = self.samples[sid]

        y_phys = s["y"][tid]          # [K,2]
        U_phys = s["U_seq"][tid]      # [N,3]

        y_flat = y_phys.reshape(1, -1)
        U_flat = U_phys.reshape(1, -1)

        y_norm_flat = ((y_flat - self.y_mean) / self.y_std).reshape(-1).astype(np.float32)
        U_norm_flat = ((U_flat - self.U_mean) / self.U_std).reshape(-1).astype(np.float32)

        return {
            "y_norm": torch.from_numpy(y_norm_flat),
            "y_phys": torch.from_numpy(y_phys.astype(np.float32)),
            "U_norm": torch.from_numpy(U_norm_flat),
            "U_phys": torch.from_numpy(U_phys.astype(np.float32)),
            "X0": torch.from_numpy(s["X0"].astype(np.float32)),
            "W_idx": torch.from_numpy(s["W_idx"].astype(np.int64)),
            "W_val": torch.from_numpy(s["W_val"].astype(np.float32)),
            "camera_K": torch.from_numpy(s["camera_K"].astype(np.float32)),
            "camera_R": torch.from_numpy(s["camera_R"].astype(np.float32)),
            "camera_t": torch.from_numpy(s["camera_t"].astype(np.float32)),
            "sample_id": torch.tensor(sid, dtype=torch.long),
            "frame_id": torch.tensor(tid, dtype=torch.long),
        }


# ============================================================
# Model: y -> z -> U + W
# ============================================================

def make_checkpoint(model, epoch, best_metric, dataset, args):
    return {
        "model_state_dict": model.state_dict(),
        "epoch": epoch,
        "best_metric": best_metric,

        "model_type": "JointUWProbabilisticMLP",
        "y_dim": dataset.y_dim,
        "U_dim": dataset.U_dim,
        "K_obs": dataset.K,
        "N_vertices": dataset.N,
        "z_dim": args.z_dim,
        "hidden_dim": args.hidden_dim,
        "logvar_min": args.logvar_min,
        "logvar_max": args.logvar_max,

        "lambda_obs": args.lambda_obs,
        "lambda_U": args.lambda_U,
        "lambda_W": args.lambda_W,
        "beta_kl": args.beta_kl,
        "normalize_y_for_projection": bool(not args.no_normalize_y_for_projection),
    }


def train(args):
    set_seed(args.seed)

    os.makedirs(args.weight_dir, exist_ok=True)
    os.makedirs(args.log_dir, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")

    print("Using device:", device)
    print("data_dir:", os.path.abspath(args.data_dir))
    print("lambda_obs:", args.lambda_obs)
    print("lambda_U:", args.lambda_U)
    print("lambda_W:", args.lambda_W)
    print("beta_kl:", args.beta_kl)
    print("sample_z:", not args.no_sample_z)
    print("logvar range:", args.logvar_min, args.logvar_max)

    dataset = SurfaceFrameDataset(args.data_dir)

    # Save normalization.
    norm_path = os.path.join(args.weight_dir, "normalization.npz")
    np.savez(
        norm_path,
        y_mean=dataset.y_mean,
        y_std=dataset.y_std,
        U_mean=dataset.U_mean,
        U_std=dataset.U_std,
    )
    print("Saved normalization to:", norm_path)

    # Torch constants for denormalization.
    U_mean_t = torch.from_numpy(dataset.U_mean.astype(np.float32)).to(device)  # [1,U_dim]
    U_std_t = torch.from_numpy(dataset.U_std.astype(np.float32)).to(device)    # [1,U_dim]

    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        drop_last=False,
        pin_memory=torch.cuda.is_available() and not args.cpu,
    )

    model = JointUWProbabilisticMLP(
        y_dim=dataset.y_dim,
        U_dim=dataset.U_dim,
        K_obs=dataset.K,
        N_vertices=dataset.N,
        z_dim=args.z_dim,
        hidden_dim=args.hidden_dim,
        logvar_min=args.logvar_min,
        logvar_max=args.logvar_max,
        dropout=args.dropout,
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    best_metric = float("inf")
    best_path = os.path.join(args.weight_dir, args.save_name)
    last_path = os.path.join(args.weight_dir, "last_" + args.save_name)
    log_path = os.path.join(args.log_dir, "train_log_joint_UW.csv")

    with open(log_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "epoch",
            "loss",
            "obs_loss_predW",
            "obs_loss_gtW",
            "U_nll",
            "U_mse_norm",
            "U_rmse_norm",
            "W_ce",
            "W_top1_acc",
            "kl",
            "mean_U_std_norm",
            "best_metric",
        ])

    sample_z = not args.no_sample_z
    normalize_y_for_projection = not args.no_normalize_y_for_projection

    for epoch in range(args.epochs):
        model.train()

        total_loss = 0.0
        total_obs = 0.0
        total_obs_gtW = 0.0
        total_U_nll = 0.0
        total_U_mse = 0.0
        total_W_ce = 0.0
        total_W_acc = 0.0
        total_kl = 0.0
        total_std = 0.0

        for batch in loader:
            y_norm = batch["y_norm"].to(device, non_blocking=True)       # [B,2K]
            y_phys = batch["y_phys"].to(device, non_blocking=True)       # [B,K,2]
            U_norm = batch["U_norm"].to(device, non_blocking=True)       # [B,3N]
            U_phys_gt = batch["U_phys"].to(device, non_blocking=True)    # [B,N,3]

            X0 = batch["X0"].to(device, non_blocking=True)               # [B,N,3]
            W_idx = batch["W_idx"].to(device, non_blocking=True)         # [B,K,3]
            W_val = batch["W_val"].to(device, non_blocking=True)         # [B,K,3]

            camera_K = batch["camera_K"].to(device, non_blocking=True)
            camera_R = batch["camera_R"].to(device, non_blocking=True)
            camera_t = batch["camera_t"].to(device, non_blocking=True)

            U_mu_norm, U_logvar_norm, W_logits, z_mu, z_logvar = model(
                y_norm,
                sample_z=sample_z,
            )

            B = y_norm.shape[0]

            # Denormalize U for observation operator.
            U_mu_phys_flat = U_mu_norm * U_std_t + U_mean_t
            U_mu_phys = U_mu_phys_flat.view(B, dataset.N, 3)

            # Observation loss using predicted W.
            y_hat_predW, W_soft = observation_operator_softW(
                U_phys=U_mu_phys,
                W_logits=W_logits,
                X0=X0,
                Kmat=camera_K,
                R=camera_R,
                t=camera_t,
                normalize_y=normalize_y_for_projection,
            )
            obs_loss_predW = torch.mean((y_hat_predW - y_phys) ** 2)

            # Oracle observation loss using GT W. This is logged and can optionally be used.
            y_hat_gtW = observation_operator_gtW(
                U_phys=U_mu_phys,
                X0=X0,
                sparse_idx=W_idx,
                sparse_val=W_val,
                Kmat=camera_K,
                R=camera_R,
                t=camera_t,
                normalize_y=normalize_y_for_projection,
            )
            obs_loss_gtW = torch.mean((y_hat_gtW - y_phys) ** 2)

            if args.use_gtW_obs_loss:
                obs_loss = obs_loss_gtW
            else:
                obs_loss = obs_loss_predW

            # U auxiliary probabilistic reconstruction in normalized U-space.
            U_nll = gaussian_nll_loss(U_norm, U_mu_norm, U_logvar_norm)
            U_mse_norm = mse_loss(U_norm, U_mu_norm)

            # W supervision from sparse barycentric GT.
            W_ce = soft_ce_loss_from_sparse(W_logits, W_idx, W_val)

            # KL regularization.
            kl = kl_loss(z_mu, z_logvar)

            loss = (
                args.lambda_obs * obs_loss
                + args.lambda_U * U_nll
                + args.lambda_W * W_ce
                + args.beta_kl * kl
            )

            optimizer.zero_grad(set_to_none=True)
            loss.backward()

            if args.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)

            optimizer.step()

            with torch.no_grad():
                U_std_norm = torch.exp(0.5 * U_logvar_norm)

                # W top-1 accuracy: predicted dominant vertex vs GT dominant bary vertex.
                pred_top = torch.argmax(W_logits, dim=-1)          # [B,K]
                gt_top_local = torch.argmax(W_val, dim=-1)         # [B,K]
                gt_top = torch.gather(W_idx, dim=-1, index=gt_top_local.unsqueeze(-1)).squeeze(-1)
                W_top1_acc = (pred_top == gt_top).float().mean()

            total_loss += float(loss.item())
            total_obs += float(obs_loss_predW.item())
            total_obs_gtW += float(obs_loss_gtW.item())
            total_U_nll += float(U_nll.item())
            total_U_mse += float(U_mse_norm.item())
            total_W_ce += float(W_ce.item())
            total_W_acc += float(W_top1_acc.item())
            total_kl += float(kl.item())
            total_std += float(U_std_norm.mean().item())

        nb = len(loader)
        avg_loss = total_loss / nb
        avg_obs = total_obs / nb
        avg_obs_gtW = total_obs_gtW / nb
        avg_U_nll = total_U_nll / nb
        avg_U_mse = total_U_mse / nb
        avg_U_rmse = float(np.sqrt(avg_U_mse))
        avg_W_ce = total_W_ce / nb
        avg_W_acc = total_W_acc / nb
        avg_kl = total_kl / nb
        avg_std = total_std / nb

        # Best model selection.
        # Use total loss by default because this is joint training.
        if args.select_best_by == "loss":
            current_metric = avg_loss
        elif args.select_best_by == "obs":
            current_metric = avg_obs
        elif args.select_best_by == "U_mse":
            current_metric = avg_U_mse
        elif args.select_best_by == "W_ce":
            current_metric = avg_W_ce
        else:
            raise ValueError(f"Unknown select_best_by: {args.select_best_by}")

        if current_metric < best_metric:
            best_metric = current_metric
            ckpt = make_checkpoint(model, epoch, best_metric, dataset, args)
            if args.safe_save:
                safe_torch_save(ckpt, best_path)
            else:
                torch.save(ckpt, best_path)

        if args.save_last and ((epoch % args.save_last_every == 0) or (epoch == args.epochs - 1)):
            ckpt = make_checkpoint(model, epoch, best_metric, dataset, args)
            if args.safe_save:
                safe_torch_save(ckpt, last_path)
            else:
                torch.save(ckpt, last_path)

        with open(log_path, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([
                epoch,
                avg_loss,
                avg_obs,
                avg_obs_gtW,
                avg_U_nll,
                avg_U_mse,
                avg_U_rmse,
                avg_W_ce,
                avg_W_acc,
                avg_kl,
                avg_std,
                best_metric,
            ])

        if epoch % args.print_every == 0:
            print(
                f"Epoch {epoch:04d} | "
                f"loss={avg_loss:.6e} | "
                f"obs_predW={avg_obs:.6e} | "
                f"obs_gtW={avg_obs_gtW:.6e} | "
                f"U_nll={avg_U_nll:.6e} | "
                f"U_rmse_norm={avg_U_rmse:.6e} | "
                f"W_ce={avg_W_ce:.6e} | "
                f"W_acc={avg_W_acc:.4f} | "
                f"kl={avg_kl:.6e} | "
                f"mean_U_std_norm={avg_std:.6e} | "
                f"best={best_metric:.6e}"
            )

    print("\nTraining finished.")
    print("Best model saved to:", best_path)
    if args.save_last:
        print("Last model saved to:", last_path)
    print("Normalization saved to:", norm_path)
    print("Log saved to:", log_path)
    print("Best metric:", best_metric)


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--data_dir", type=str, default=DEFAULT_DATA_DIR)
    parser.add_argument("--weight_dir", type=str, default=DEFAULT_WEIGHT_DIR)
    parser.add_argument("--log_dir", type=str, default=DEFAULT_LOG_DIR)
    parser.add_argument("--save_name", type=str, default="joint_UW_surface_best.pth")

    parser.add_argument("--epochs", type=int, default=2000)
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-6)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--z_dim", type=int, default=32)
    parser.add_argument("--hidden_dim", type=int, default=256)
    parser.add_argument("--dropout", type=float, default=0.0)

    # Loss weights.
    # Suggested stable start:
    #   lambda_U keeps deformation physically meaningful.
    #   lambda_W teaches correspondence.
    #   lambda_obs closes the inverse loop through the camera.
    parser.add_argument("--lambda_obs", type=float, default=10.0)
    parser.add_argument("--lambda_U", type=float, default=1.0)
    parser.add_argument("--lambda_W", type=float, default=0.1)
    parser.add_argument("--beta_kl", type=float, default=1e-4)

    # U uncertainty in normalized U-space.
    parser.add_argument("--logvar_min", type=float, default=-8.0)
    parser.add_argument("--logvar_max", type=float, default=2.0)

    parser.add_argument("--grad_clip", type=float, default=1.0)
    parser.add_argument("--print_every", type=int, default=50)

    parser.add_argument(
        "--select_best_by",
        type=str,
        default="loss",
        choices=["loss", "obs", "U_mse", "W_ce"],
    )

    # Debug / ablation flags.
    parser.add_argument(
        "--use_gtW_obs_loss",
        action="store_true",
        help="Use GT W for observation loss. Useful as oracle/debug. Default uses predicted W.",
    )
    parser.add_argument(
        "--no_normalize_y_for_projection",
        action="store_true",
        help="If set, observation projection loss is computed in pixel units. Default uses y_pixel/fx units.",
    )
    parser.add_argument("--no_sample_z", action="store_true")
    parser.add_argument("--cpu", action="store_true")

    parser.add_argument("--safe_save", action="store_true", default=True)
    parser.add_argument("--save_last", action="store_true")
    parser.add_argument("--save_last_every", type=int, default=100)

    return parser.parse_args()

if __name__ == "__main__":
    train(parse_args())
